# Generated by Django 4.2.5 on 2023-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta orqali')], default='card', max_length=50, verbose_name="To'lov turi"),
        ),
    ]
