# Generated by Django 4.2.7 on 2023-11-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sponser_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponser',
            old_name='orgsnization_name',
            new_name='organization_name',
        ),
    ]
