# Generated by Django 4.2.5 on 2023-11-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_orgsnization_name_sponser_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponser',
            name='sponser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsers', to='api.sponser', verbose_name='Sponser'),
        ),
        migrations.AlterField(
            model_name='studentsponser',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sponsers', to='api.student', verbose_name='Student'),
        ),
    ]
