# Generated by Django 4.2.5 on 2023-11-09 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studentsponser_sponser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='phone_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Telefon raqami'),
        ),
    ]
