# Generated by Django 4.2.5 on 2023-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sponser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefon raqami'),
        ),
    ]
