# Generated by Django 4.2.5 on 2023-11-11 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sponser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='phone_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\998\\d{9}$')], verbose_name='Telefon raqami'),
        ),
    ]
